Repository hugovk/em-keyboard, pull requests merged in 2023-09, with the labels that each got.

#124 Upgrade to emojilib 3.0.11
  .github/workflows/deploy.yml
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  scripts/update-emojilib.sh
  src/em_keyboard/emoji-en-US.json
  src/em_keyboard/emojis.json
  tox.ini
Labels: changelog: Added

#127 Additional tests
  tests/test_em.py
Labels: changelog: skip

#128 Add PR write permission for github-action-required-labels
  .github/workflows/require-pr-label.yml
Labels: changelog: skip

#126 Use `importlib.resources` instead of `__file__`
  src/em_keyboard/__init__.py
Labels: changelog: Changed
