Repository hugovk/em-keyboard, pull requests merged in 2025-01, with the labels that each got.

#157 Allow more than one search word
  src/em_keyboard/__init__.py
  tests/test_em.py
Labels: changelog: Added

#155 Depend on `pyperclip` on all platforms
  README.md
  pyproject.toml
  src/em_keyboard/__init__.py
  tests/test_em.py
Labels: changelog: Added

#162 Don't print empty line when emoji not found
  src/em_keyboard/__init__.py
  tests/test_em.py
Labels: changelog: Fixed

#160 Fix warning[excessive-permissions]: overly broad permissions
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: changelog: skip

#159 Small optimisations
  src/em_keyboard/__init__.py
Labels: changelog: Changed

#163 Remove temporary emoji database copy from wheel and sdist
  pyproject.toml
Labels: changelog: Changed

#164 Improve keyword normalization
  scripts/despacify.py
  src/em_keyboard/__init__.py
  src/em_keyboard/emojis.json
Labels: changelog: Changed

#166 Rename `em_keyboard` package to `em` and refactor
  .coveragerc
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  scripts/despacify.py
  scripts/update-emojilib.sh
  src/em/__init__.py
  src/em/__main__.py
  src/em/cli.py
  src/em/emoji-en-US.json
  src/em/emojis.json
  tests/test_em.py
  tox.ini
Labels: changelog: Changed

#165 Only create PyPI digital attestations (PEP 740)
  .github/workflows/deploy.yml
Labels: changelog: Removed

#168 Require hatchling>=1.27 for licence expressions (PEP 639)
  pyproject.toml
Labels: changelog: skip
